### ISSUE TITLE
Change amazonapac to be served from generic-mm3 bucket

### ISSUE THREAD

**Issue by Beslinda** [mediafellows/mfx-ui-config#27]
`amazonapac` currently is served from the old generic bucket, please change it to be served from the new  `generic-mm3`

**Comment by stefanhorning** [comment]
I guess we should also set the BE flag to true for `uses_mm3_assets`

**Comment by stefanhorning** [comment]
FE infra PR:
- https://github.com/mediafellows/fe-infrastructure/pull/180

**Comment by stefanhorning** [comment]
FE domain change and `uses_mm3_assets=true` rolled out to:
- [ ] staging
- [ ] presentation
- [ ] production
